/**
 * The diff engine: compares a parsed HelpSurface against the DocsSurface
 * recovered from Markdown and emits stable-coded findings.
 *
 * Codes are API and are never renumbered:
 *   D101 error   undocumented flag         (help has it, docs never mention it)
 *   D102 error   phantom flag              (docs mention it, help does not have it)
 *   D103 warning stale default             (docs table default ≠ help default)
 *   D104 warning value drift               (docs attach a value to a boolean flag)
 *   D105 warning undocumented subcommand
 *   D106 error   phantom subcommand
 *   D107 info    deprecated but documented without a deprecation note
 *   D108 info    short alias never shown in the docs
 */

import type {
  DocFlagOccurrence,
  DocsSurface,
  DriftOptions,
  Finding,
  HelpFlag,
  HelpSurface,
  Severity,
} from "./types.js";
import { spellingsOf } from "./helpparse.js";

/**
 * Spellings never reported as undocumented or phantom: virtually every
 * CLI has them, and many helps omit them, so both directions are noise.
 */
const WELL_KNOWN_FLAGS = new Set(["--help", "--version", "-h", "-V"]);

/** Subcommands auto-generated by cobra/clap that docs rarely list. */
const WELL_KNOWN_COMMANDS = new Set(["help", "completion", "completions"]);

const SEVERITY_RANK: Record<Severity, number> = { error: 0, warning: 1, info: 2 };

/** Compare the two surfaces and return sorted findings. */
export function diffSurfaces(
  help: HelpSurface,
  docs: DocsSurface,
  opts: DriftOptions = {},
): Finding[] {
  const ignore = compileIgnore(opts.ignore ?? []);
  const findings: Finding[] = [];

  // Index every help spelling → its flag.
  const bySpelling = new Map<string, HelpFlag>();
  for (const flag of help.flags) {
    for (const s of spellingsOf(flag)) {
      if (!bySpelling.has(s)) bySpelling.set(s, flag);
    }
  }

  // Index docs occurrences by the flag they resolve to (or their spelling).
  const docOcc = new Map<HelpFlag, DocFlagOccurrence[]>();
  const phantom = new Map<string, DocFlagOccurrence>();
  for (const occ of docs.flags) {
    const flag = bySpelling.get(occ.flag);
    if (flag) {
      const list = docOcc.get(flag) ?? [];
      list.push(occ);
      docOcc.set(flag, list);
    } else if (!phantom.has(occ.flag)) {
      phantom.set(occ.flag, occ);
    }
  }

  // ---- help-side checks -------------------------------------------------
  for (const flag of help.flags) {
    if (matchesIgnore(ignore, spellingsOf(flag))) continue;
    const occurrences = docOcc.get(flag) ?? [];

    if (occurrences.length === 0) {
      if (flag.deprecated) continue; // hiding deprecated flags is deliberate
      if (spellingsOf(flag).every((s) => WELL_KNOWN_FLAGS.has(s))) continue;
      findings.push(d101(flag));
      continue;
    }

    for (const occ of occurrences) {
      if (
        occ.defaultValue !== undefined &&
        flag.defaultValue !== undefined &&
        !defaultsEqual(occ.defaultValue, flag.defaultValue)
      ) {
        findings.push(d103(flag, occ));
      }
      if (occ.attachedValue !== undefined && !flag.takesValue) {
        findings.push(d104(flag, occ));
      }
    }

    if (flag.deprecated && !occurrences.some((o) => o.deprecatedNote)) {
      findings.push(d107(flag, occurrences[0]));
    }

    const shorts = spellingsOf(flag).filter(
      (s) => /^-[A-Za-z0-9?]$/.test(s) && !WELL_KNOWN_FLAGS.has(s),
    );
    if (shorts.length > 0 && !flag.deprecated) {
      const shown = occurrences.some((o) => shorts.includes(o.flag));
      if (!shown) findings.push(d108(flag, shorts));
    }
  }

  // ---- docs-side checks -------------------------------------------------
  for (const [spelling, occ] of phantom) {
    if (WELL_KNOWN_FLAGS.has(spelling)) continue;
    if (matchesIgnore(ignore, [spelling])) continue;
    findings.push(d102(spelling, occ, help));
  }

  // ---- subcommand checks (only when the help lists any) ------------------
  if (help.commands.length > 0) {
    const helpNames = new Set<string>();
    for (const c of help.commands) {
      helpNames.add(c.name);
      for (const a of c.aliases) helpNames.add(a);
    }
    const documented = new Set(docs.commands.map((c) => c.name));

    for (const cmd of help.commands) {
      if (WELL_KNOWN_COMMANDS.has(cmd.name)) continue;
      if (matchesIgnore(ignore, [cmd.name, ...cmd.aliases])) continue;
      const shown = cmd.name && ([cmd.name, ...cmd.aliases].some((n) => documented.has(n)));
      if (!shown) {
        findings.push({
          code: "D105",
          severity: "warning",
          subject: cmd.name,
          message: `the live --help lists a \`${cmd.name}\` subcommand that the docs never invoke`,
          fix: `show at least one \`… ${cmd.name}\` invocation, or pass --ignore '${cmd.name}'`,
        });
      }
    }

    const seenPhantomCmd = new Set<string>();
    for (const occ of docs.commands) {
      if (helpNames.has(occ.name)) continue;
      if (WELL_KNOWN_COMMANDS.has(occ.name)) continue;
      if (matchesIgnore(ignore, [occ.name])) continue;
      if (seenPhantomCmd.has(occ.name)) continue;
      seenPhantomCmd.add(occ.name);
      const near = nearest(occ.name, [...helpNames]);
      findings.push({
        code: "D106",
        severity: "error",
        subject: occ.name,
        message:
          `the docs invoke a \`${occ.name}\` subcommand that the live --help does not list` +
          (near ? ` (did you mean \`${near}\`?)` : ""),
        fix: "update or remove the invocation — readers will hit an error verbatim",
        file: occ.file,
        line: occ.line,
      });
    }
  }

  return sortFindings(findings);
}

// ---- individual finding builders ------------------------------------------

function d101(flag: HelpFlag): Finding {
  const shape = flag.takesValue ? `${flag.name} <${flag.placeholder ?? "VALUE"}>` : flag.name;
  const hint = flag.defaultValue !== undefined ? ` (default: ${flag.defaultValue})` : "";
  return {
    code: "D101",
    severity: "error",
    subject: flag.name,
    message: `\`${shape}\` is in the live --help but never appears in the docs`,
    fix: `add it to the flag reference${hint}, or pass --ignore '${flag.name}'`,
  };
}

function d102(spelling: string, occ: DocFlagOccurrence, help: HelpSurface): Finding {
  const candidates = help.flags.flatMap((f) => spellingsOf(f));
  const near = nearest(spelling, candidates);
  return {
    code: "D102",
    severity: "error",
    subject: spelling,
    message:
      `the docs mention \`${spelling}\` but the live --help has no such flag` +
      (near ? ` (did you mean \`${near}\`?)` : ""),
    fix: "update or remove the reference — it fails for anyone who copies it",
    file: occ.file,
    line: occ.line,
  };
}

function d103(flag: HelpFlag, occ: DocFlagOccurrence): Finding {
  return {
    code: "D103",
    severity: "warning",
    subject: flag.name,
    message: `the docs say the default for \`${flag.name}\` is \`${occ.defaultValue}\`, but --help says \`${flag.defaultValue}\``,
    fix: `update the table cell to \`${flag.defaultValue}\``,
    file: occ.file,
    line: occ.line,
  };
}

function d104(flag: HelpFlag, occ: DocFlagOccurrence): Finding {
  return {
    code: "D104",
    severity: "warning",
    subject: flag.name,
    message: `the docs write \`${occ.flag}=${occ.attachedValue}\`-style usage, but --help says \`${flag.name}\` takes no value`,
    fix: "drop the value, or fix the help text if the flag really accepts one",
    file: occ.file,
    line: occ.line,
  };
}

function d107(flag: HelpFlag, occ: DocFlagOccurrence | undefined): Finding {
  return {
    code: "D107",
    severity: "info",
    subject: flag.name,
    message: `--help marks \`${flag.name}\` deprecated, but the docs present it without a deprecation note`,
    fix: "add a deprecation note next to the documented flag",
    file: occ?.file,
    line: occ?.line,
  };
}

function d108(flag: HelpFlag, shorts: string[]): Finding {
  return {
    code: "D108",
    severity: "info",
    subject: flag.name,
    message: `\`${flag.name}\` has the short form \`${shorts[0]}\`, which the docs never show`,
    fix: `mention \`${shorts[0]}\` in the flag reference`,
  };
}

// ---- helpers ---------------------------------------------------------------

interface IgnorePattern {
  exact?: string;
  prefix?: string;
}

function compileIgnore(patterns: string[]): IgnorePattern[] {
  return patterns.map((p) =>
    p.endsWith("*") ? { prefix: p.slice(0, -1) } : { exact: p },
  );
}

function matchesIgnore(patterns: IgnorePattern[], spellings: string[]): boolean {
  return spellings.some((s) =>
    patterns.some((p) =>
      p.exact !== undefined ? p.exact === s : s.startsWith(p.prefix ?? ""),
    ),
  );
}

/**
 * Compare a docs default against a help default, forgiving formatting:
 * backticks and quotes are stripped, booleans compare case-insensitively,
 * numbers compare numerically (`3` == `3.0`).
 */
export function defaultsEqual(docsValue: string, helpValue: string): boolean {
  const a = strip(docsValue);
  const b = strip(helpValue);
  if (a === b) return true;
  if (/^(true|false|yes|no|on|off)$/i.test(a) && a.toLowerCase() === b.toLowerCase()) {
    return true;
  }
  const na = Number(a);
  const nb = Number(b);
  if (a !== "" && b !== "" && !Number.isNaN(na) && !Number.isNaN(nb)) {
    return na === nb;
  }
  return false;
}

function strip(v: string): string {
  return v.trim().replace(/^["'`]|["'`]$/g, "").trim();
}

/** Closest candidate within an edit distance of 3 (did-you-mean). */
export function nearest(word: string, candidates: string[]): string | undefined {
  let best: string | undefined;
  let bestDist = 4;
  for (const c of candidates) {
    const d = levenshtein(word, c);
    if (d < bestDist) {
      bestDist = d;
      best = c;
    }
  }
  return best;
}

function levenshtein(a: string, b: string): number {
  if (a === b) return 0;
  const prev = new Array<number>(b.length + 1);
  const cur = new Array<number>(b.length + 1);
  for (let j = 0; j <= b.length; j++) prev[j] = j;
  for (let i = 1; i <= a.length; i++) {
    cur[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      cur[j] = Math.min(
        (prev[j] ?? 0) + 1,
        (cur[j - 1] ?? 0) + 1,
        (prev[j - 1] ?? 0) + cost,
      );
    }
    for (let j = 0; j <= b.length; j++) prev[j] = cur[j] ?? 0;
  }
  return prev[b.length] ?? 0;
}

function sortFindings(findings: Finding[]): Finding[] {
  return findings.sort((x, y) => {
    const s = SEVERITY_RANK[x.severity] - SEVERITY_RANK[y.severity];
    if (s !== 0) return s;
    if (x.code !== y.code) return x.code < y.code ? -1 : 1;
    if (x.subject !== y.subject) return x.subject < y.subject ? -1 : 1;
    return (x.line ?? 0) - (y.line ?? 0);
  });
}

/** Tally findings by severity. */
export function summarize(findings: Finding[]): {
  errors: number;
  warnings: number;
  infos: number;
} {
  let errors = 0;
  let warnings = 0;
  let infos = 0;
  for (const f of findings) {
    if (f.severity === "error") errors++;
    else if (f.severity === "warning") warnings++;
    else infos++;
  }
  return { errors, warnings, infos };
}
